services:
  php:
    # Esta imagen siempre funciona y trae PHP 8.4
    image: php:8.4-fpm-bookworm
    container_name: tartas_php
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: "mysql://app:root@database:3306/tartas_tania?serverVersion=mariadb-10.11.2"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - tartas_net
    # Instalamos lo necesario y levantamos el servidor interno de Symfony
    entrypoint: ["sh", "-c", "apt-get update && apt-get install -y unzip libicu-dev && docker-php-ext-install pdo_mysql intl && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && php -S 0.0.0.0:8000 -t public"]

  database:
    image: mariadb:10.11
    container_name: tartas_db
    environment:
      MARIADB_DATABASE: tartas_tania
      MARIADB_USER: app
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - tartas_net
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "app", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database_data:

networks:
  tartas_net:
    driver: bridge
