version: "3.8"

services:
  php:
    image: php:8.4-cli
    container_name: tartas_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8001:8000"
    depends_on:
      - database
    tty: true
    stdin_open: true
    networks:
      - tartas_net
    command: tail -f /dev/null

  database:
    image: postgres:16-alpine
    container_name: tartas_db
    environment:
      POSTGRES_DB: tartas_tania
      POSTGRES_USER: app
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - tartas_net
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "tartas_tania", "-U", "app"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: tartas_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - tartas_net

volumes:
  database_data:

networks:
  tartas_net:
    driver: bridge
